apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: <PROJECT_NAME>
  name: <PROJECT_NAME>
  namespace: <NAMESPACE>
spec:
  ports:
    - name: http
      port: <SERVICE_PORT>
      protocol: TCP
      targetPort: <JAR_PORT>
  selector:
    app: <PROJECT_NAME>
  type: ClusterIP