apiVersion: apps/v1
kind: Deployment
metadata:
  name: <PROJECT_NAME>
  namespace: <NAMESPACE>
  labels:
    app: <PROJECT_NAME>
    k8s.kuboard.cn/layer: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <PROJECT_NAME>
  template:
    metadata:
      labels:
        app: <PROJECT_NAME>
    spec:
      containers:
        - name: <PROJECT_NAME>
          image: <REGISTRY>/<DOCKERHUB_NAMESPACE>/<PROJECT_NAME>:SNAPSHOT-<BUILD_NUMBER>
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - name: http-server
              containerPort: <JAR_PORT>
      imagePullSecrets:
        - name: <HARBOR_SECRET>